config/routes.rb
Rails.application.routes.draw do
  get 'grid/(:court_id)', to: 'dashboard#grid', as: 'dashboard_grid'
  get 'products/show'

  concern :bookable do 
    resources :events
    resources :my_events
    collection do 
      get 'events', to: 'events#parents_events'
    end
  end
  concern :totalable do 
    member do 
      get 'total'
    end
  end

  concern :has_pictures do 
    resources :pictures
  end
  concern :has_special_prices do 
    resources :special_prices
  end

  resources :events, :my_events do 
    collection do 
      get 'paid'
      get 'grid'
      post 'bulk_process', constraints: ButtonParamRouting.new('pay'), action: 'create', controller: 'orders'
      post 'bulk_process', constraints: ButtonParamRouting.new('destroy'), action: 'destroy'
    end
  end

  resources :products, concerns: :bookable

  # scope :my do
    # resources :courts
  # end

  post 'feedback/create', as: 'feedback'

  resources :static_pages, only: :show

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  namespace :admin do
    resources :users
  end
  # resources :changes, only: :create

  post 'payments/success'

  resources :orders do
    member do
      patch 'pay'
    end
  end



  namespace :admin do
    resources :stadiums
    resources :users
    resource :options,  only: [:edit, :update]
    resources :static_pages
    resources :categories
    root to: 'stadiums#index'
  end

  # constraints RoleRouteConstraint.new('stadium_user') do
  #   namespace :dashboard do
  #     scope module: :stadium do
  #       resource :stadium do
  #         resources :pictures, defaults: { imageable_type: 'Stadium'}
  #         resources :coaches
  #       end
  #       resources :courts, concerns: :bookable do
  #         resources :special_prices
  #       end
  #       resources :orders
  #        do
  #         member do
  #           get 'confirm'
  #         end
  #       end
  #       get 'orders', to: 'orders#index', as: 'wallet'
  #     end
  #   end
  # end

  # constraints RoleRouteConstraint.new('coach_user') do

  namespace :dashboard do
    resource :product, concerns: [:has_pictures]
    resources :special_prices
    # resource :events
    resources :customers
    resources :employments
    resources :coach_users
    resources :withdrawal_requests
    # resources :orders
  end

  resources :deposit_requests

  constraints RoleRouteConstraint.new('admin') do
    namespace :dashboard do
      scope module: :customer do
        resources :orders do
          member do
            patch 'pay'
          end
        end
      end
    end
  end
  # scope '(:scope)' do 
  resources :courts, concerns: [:bookable, :totalable]
  # end
  resources :coaches, defaults: { scope: 'coach' } do 
    resources :courts, concerns: [:bookable, :totalable]
  end

  resources :stadiums, defaults: { scope: 'stadium' } do
    resources :events
    resources :pictures, only: :index
    resources :reviews
    resources :courts, concerns: [:bookable, :totalable]
  end

  # get 'events/grid', to: 'events#grid', as: 'dashboard'

  resources :stadium_users
  resources :sales

  get 'categories/:category_id', to: 'stadiums#index', as: 'category'

  root to: 'visitors#index'
  devise_for :users
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  def index
    @stadiums = Stadium.where('status <> ?', Stadium.statuses[:pending])
  end
end

app/views/visitors/index.html.erb
<%= render 'map' %>
<div class="body-bg">
  <div class="homepage-container">
  	  <h1><span class="title-tire">&#8211;</span> СПОРТИВНЫЕ ОБЪЕКТЫ ДЛЯ БРОНИРОВАНИЯ <span class="title-tire">&#8211;</span></h1>
  <div class="row">
    <%= link_to category_path('tennis') do %>
      <div class="col-md-8 homepage-categories-first"><div class="homepage-txt-block"><div class="hpt-border">Теннис</div></div></div>
    <% end %>
    <%= link_to category_path('futbol') do %>
      <div class="col-md-4 homepage-categories-second"><div class="homepage-txt-block"><div class="hpt-border">Футбол</div></div></div>
    <% end %>
  </div>
  <div class="row">
    <%= link_to category_path('gruppovye-zanyatiya') do %>
      <div class="col-xs-12 col-sm-6 col-md-6 image-grid-item homepage-categories-third"><div class="homepage-txt-block"><div class="hpt-border">Групповые занятия</div></div></div>
    <% end %>
    <%= link_to category_path('fitness') do %>
      <div class="col-xs-12 col-sm-6 col-md-3 image-grid-item homepage-categories-fourth"><div class="homepage-txt-block"><div class="hpt-border">Фитнес</div></div></div>
    <% end %>
    <%= link_to category_path('yoga') do %>
      <div class="col-xs-12 col-sm-6 col-md-3 image-grid-item homepage-categories-fifth"><div class="homepage-txt-block"><div class="hpt-border">Йога</div></div></div>
    <% end %>
    </div>
  </div>
</div>