config/routes.rb
Rails.application.routes.draw do
  get 'grid/(:court_id)', to: 'dashboard#grid', as: 'dashboard_grid'
  get 'products/show'

  concern :bookable do 
    resources :events
    resources :my_events
    collection do 
      get 'events', to: 'events#parents_events'
    end
  end
  concern :totalable do 
    member do 
      get 'total'
    end
  end

  concern :has_pictures do 
    resources :pictures
  end
  concern :has_special_prices do 
    resources :special_prices
  end

  resources :events, :my_events do 
    collection do 
      get 'paid'
      get 'grid'
      post 'bulk_process', constraints: ButtonParamRouting.new('pay'), action: 'create', controller: 'orders'
      post 'bulk_process', constraints: ButtonParamRouting.new('destroy'), action: 'destroy'
    end
  end

  resources :products, concerns: :bookable

  # scope :my do
    # resources :courts
  # end

  post 'feedback/create', as: 'feedback'

  resources :static_pages, only: :show

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  namespace :admin do
    resources :users
  end
  # resources :changes, only: :create

  post 'payments/success'

  resources :orders do
    member do
      patch 'pay'
    end
  end



  namespace :admin do
    resources :stadiums
    resources :users
    resource :options,  only: [:edit, :update]
    resources :static_pages
    resources :categories
    root to: 'stadiums#index'
  end

  # constraints RoleRouteConstraint.new('stadium_user') do
  #   namespace :dashboard do
  #     scope module: :stadium do
  #       resource :stadium do
  #         resources :pictures, defaults: { imageable_type: 'Stadium'}
  #         resources :coaches
  #       end
  #       resources :courts, concerns: :bookable do
  #         resources :special_prices
  #       end
  #       resources :orders
  #        do
  #         member do
  #           get 'confirm'
  #         end
  #       end
  #       get 'orders', to: 'orders#index', as: 'wallet'
  #     end
  #   end
  # end

  # constraints RoleRouteConstraint.new('coach_user') do

  namespace :dashboard do
    resource :product, concerns: [:has_pictures]
    resources :special_prices
    # resource :events
    resources :customers
    resources :employments
    resources :coach_users
    resources :withdrawal_requests
    # resources :orders
  end

  resources :deposit_requests

  constraints RoleRouteConstraint.new('admin') do
    namespace :dashboard do
      scope module: :customer do
        resources :orders do
          member do
            patch 'pay'
          end
        end
      end
    end
  end
  # scope '(:scope)' do 
  resources :courts, concerns: [:bookable, :totalable]
  # end
  resources :coaches, defaults: { scope: 'coach' } do 
    resources :courts, concerns: [:bookable, :totalable]
  end

  resources :stadiums, defaults: { scope: 'stadium' } do
    resources :events
    resources :pictures, only: :index
    resources :reviews
    resources :courts, concerns: [:bookable, :totalable]
  end

  # get 'events/grid', to: 'events#grid', as: 'dashboard'

  resources :stadium_users
  resources :sales

  get 'categories/:category_id', to: 'stadiums#index', as: 'category'

  root to: 'visitors#index'
  devise_for :users
end

app/models/user.rb
class User < ActiveRecord::Base
  default_scope { order(created_at: :desc) }
  # include FriendlyId
  # friendly_id :name, use: [:slugged]

  has_many :orders, dependent: :destroy
  has_many :events
  has_many :event_changes, through: :events
  has_one :wallet, dependent: :destroy
  has_many :special_prices
  after_create :create_wallet

  after_initialize :set_customer, if: :new_record?

  validates_acceptance_of :terms_agree

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def set_customer
    self.type = 'Customer' unless self.type
  end

  def public_type= type
    if type == 'Admin'
      raise 'Нельзя стать админом просто так!'
    elsif ['StadiumUser', 'CoachUser', 'Customer'].include? type
      self.becomes! type.constantize
    end
  end

  def total options={}
    events_maybe_scoped_by(options).unpaid.map(&:total).inject(:+)
  end

  def total_hours options={}
    events_maybe_scoped_by(options).unpaid.map(&:duration_in_hours).inject(:+) || 0
  end

  def events_maybe_scoped_by options
    if options[:product].present?
      events.of_products(options[:product])
    else
      events
    end
  end

  def changes_total options={}
    event_changes.of_products(options[:product]).unpaid.map(&:total).inject(:+) || 0
  end

  def navs
    []
  end

  def method_missing t
    if t.to_s.ends_with? '?'
      type == t.to_s.to(-2).camelcase
    end
  end

  def name_for_admin
    name.to_s + " (#{email})"
  end

  def admin?
    false
  end

  def new_event options={}
    self.events.new options
  end
end

app/controllers/my_events_controller.rb
class MyEventsController < EventsController
  layout 'dashboard'
  def index
    @events = current_user.events.order(created_at: :desc)
        
    respond_to do |format|
      format.json {@events = @events.of_products(current_products)}
      format.html {}
    end
  end

  def paid
    @events = current_user.product.events.order(created_at: :desc)
  end

  def grid
  end

  def bulk_process
    # case params[:button]
    # when 'delete'
    #   render action: :destroy
    # when 'pay'
    #   render 'orders/create' 
    # else
    #   redirect_to my_events_path, alert: "Неизвестное действие."
    # end
  end

  def destroy
    Event.where(id: params[:event_ids]).delete_all

    redirect_to my_events_path, notice: 'Успешно удалены.'
  end
end

app/helpers/my_events_helper.rb
module MyEventsHelper
end

app/views/my_events/grid.html.haml
nothing to see
-#.row.top15
  .col-md-4
    %ul.nav.nav-pills.nav-stacked
      - current_user.products.each do |product|
        = active_link_to product.name, grid_my_events_path(product_id: product), active: /#{product.to_param}/, wrap_tag: :li
  .col-md-8
    .top15{"data-grid" => ""}
    :javascript
      kendo.culture("ru-RU");
      var grid = new Tennis.Views.ScheduleView({el: '[data-grid]'});
      // var changes = new Tennis.Collections.Changes();
      // var checkout = new Tennis.Views.CheckoutView({el: '[data-checkout]'});
      // var changesView = new Tennis.Views.ChangesView({el: '[data-event-move]', collection: changes});
      grid.render();

app/views/my_events/index.html.haml
%h4 Неоплаченные занятия
= form_for :events, url: bulk_process_my_events_path do |f|
  %table.table.table-hover
    %thead
      %tr
        %th 
        %th Стадион
        %th Корт
        %th Период занятий
        %th Время тренировок
        %th Стоимость
    - @events.unpaid.each do |event|
      %tr
        %td= check_box_tag "event_ids[]", event.id
        %td= event.stadium.name
        %td= event.court.name
        %td= l(event.schedule.first.to_date) + ' - ' + l(event.schedule.last.to_date)
        %td= event.start.strftime("%H:%M:%S") + ' - ' + event.end.strftime("%H:%M:%S")
        %td= number_to_integer_currency event.total
  = f.button 'Перейти к оплате', value: :pay
  = f.button 'Удалить', value: :destroy
%h4 Оплаченные занятия
%table.table.table-striped
  %thead
    %tr
      %th #
      %th Стадион
      %th Корт
      %th Период занятий
      %th Время тренировок
      %th Стоимость
  - @events.paid.each do |event|
    %tr
      %td= event.id
      %td= event.stadium.name
      %td= event.court.name
      %td= l(event.schedule.first.to_date) + ' - ' + l(event.schedule.last.to_date)
      %td
        = event.start.strftime("%H:%M:%S") + ' - ' + event.end.strftime("%H:%M:%S")
        - if event.has_unpaid_changes?
          = link_to orders_path('event_change_ids[]' => event.event_change.id), method: :post, class: 'label' do
            %span.label.label-success Оплатить перенос
      %td= number_to_integer_currency event.total

app/views/my_events/paid.html.haml
%h4 Заказы
%table.table.table-striped.datatable
  %thead
    %tr
      %th #
      %th Стадион
      %th Корт
      %th Период занятий
      %th Время тренировок
      %th Стоимость
  - @events.paid.each do |event|
    %tr
      %td= event.id
      %td= event.stadium.name
      %td= event.court.name
      %td= l(event.schedule.first.to_date) + ' - ' + l(event.schedule.last.to_date)
      %td
        = event.start.strftime("%H:%M:%S") + ' - ' + event.end.strftime("%H:%M:%S")
        - if event.has_unpaid_changes?
          = link_to orders_path('event_change_ids[]' => event.event_change.id), method: :post, class: 'label' do
            %span.label.label-success Оплатить перенос
      %td= number_to_integer_currency event.total